In [ ]:
import numpy as np

grid = np.random.choice([-1,1],size=(500,500))
print(grid)
#creating 500x500 matrix representing the energy stage of the ising model




[[ 1 -1 -1 ...  1 -1 -1]
 [-1  1 -1 ...  1 -1 -1]
 [ 1  1  1 ...  1 -1 -1]
 ...
 [-1 -1 -1 ... -1  1  1]
 [-1  1 -1 ...  1  1  1]
 [-1  1 -1 ...  1  1 -1]]


In [6]:
#inital V_0
N = 500
sum = 0
for i in range(500):
    for j in range(500):
        tempt = -1/2 * grid[i, j] * (grid[(i + 1) % N, j]+ grid[(i - 1) % N, j]+ grid[i, (j + 1) % N]+ grid[i, (j - 1) % N])
        sum+= tempt
print(f" intial V : {sum}")


 intial V : -204.0


In [7]:

increment = 0.001
beta = 0.1
attempt = 0

while beta <= 10:
    attempt +=1
    i = np.random.randint(N)
    j = np.random.randint(N)
    neighbor_sum = (
        grid[(i + 1) % N, j]
        + grid[(i - 1) % N, j]
        + grid[i, (j + 1) % N]
        + grid[i, (j - 1) % N]
    )

    delta_V = 2 * grid[i, j] * neighbor_sum

    #accept and reject algo
    if delta_V <= 0 or np.random.random() < np.exp(-beta*delta_V):
        #flip accept
        grid[i,j]*=-1
        sum += delta_V
        
    if attempt % 500 == 0:
        beta += increment

print(sum)

-435928.0
